[package]
name = "progressus-headless"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
progressus-app = { path = "../progressus-app" }
progressus-content = { path = "../progressus-content" }

[[bin]]
name = "progressus-headless"
path = "src/main.rs"

[lints]
workspace = true
